-- ============================================
-- MODELO DE BASE DE DATOS - LUMEN LEGAL
-- ============================================


-- ============================================
-- TABLAS DE CATÁLOGO
-- ============================================

CREATE TABLE DOCUMENTO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_DOCUMENTO VARCHAR(255) UNIQUE
);


CREATE TABLE CODIGO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO VARCHAR(100) UNIQUE
);


CREATE TABLE DETALLE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    INFORMACION_DETALLE VARCHAR(500) UNIQUE
);


CREATE TABLE REFERENCIA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    REFERENCIA VARCHAR(100) UNIQUE
);


CREATE TABLE TERCEROS (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_TERCERO VARCHAR(255),
    NIT VARCHAR(20) UNIQUE
);


CREATE TABLE MES (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    MES VARCHAR(50) UNIQUE
);


CREATE TABLE ANO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ANO VARCHAR(4) UNIQUE
);


CREATE TABLE NOMBRE_ARCHIVO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE_ARCHIVO VARCHAR(255) UNIQUE
);


CREATE TABLE CLASIFICACION (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLASIFICACION VARCHAR(100) UNIQUE
);


CREATE TABLE TIPO_INGRESO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_INGRESO VARCHAR(100) UNIQUE
);


CREATE TABLE VIGENCIA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    VIGENCIA VARCHAR(100) UNIQUE
);


CREATE TABLE CLASIFICACION_NOMBRE_CUENTA (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CLASIFICACION_NOMBRE_CUENTA VARCHAR(100) UNIQUE
);


CREATE TABLE TIPO_EGRESO (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TIPO_EGRESO VARCHAR(100) UNIQUE
);


-- ============================================
-- TABLA PRINCIPAL
-- ============================================

CREATE TABLE MOVIMIENTO_CONTABLE (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,

    ID_DOCUMENTO INT,
    ID_CODIGO INT,
    ID_DETALLE INT,
    ID_REFERENCIA INT,
    ID_TERCEROS INT,
    ID_MES INT,
    ID_ANO INT,
    ID_NOMBRE_ARCHIVO INT,
    ID_CLASIFICACION INT,
    ID_TIPO_INGRESO INT,
    ID_VIGENCIA INT,
    ID_CLASIFICACION_NOMBRE_CUENTA INT,
    ID_TIPO_EGRESO INT,

    DEBITO FLOAT,
    CREDITO FLOAT,
    TOTAL FLOAT,

    FOREIGN KEY (ID_DOCUMENTO) 
        REFERENCES DOCUMENTO(ID),

    FOREIGN KEY (ID_CODIGO) 
        REFERENCES CODIGO(ID),

    FOREIGN KEY (ID_DETALLE) 
        REFERENCES DETALLE(ID),

    FOREIGN KEY (ID_REFERENCIA) 
        REFERENCES REFERENCIA(ID),

    FOREIGN KEY (ID_TERCEROS) 
        REFERENCES TERCEROS(ID),

    FOREIGN KEY (ID_MES) 
        REFERENCES MES(ID),

    FOREIGN KEY (ID_ANO) 
        REFERENCES ANO(ID),

    FOREIGN KEY (ID_NOMBRE_ARCHIVO) 
        REFERENCES NOMBRE_ARCHIVO(ID),

    FOREIGN KEY (ID_CLASIFICACION) 
        REFERENCES CLASIFICACION(ID),

    FOREIGN KEY (ID_TIPO_INGRESO) 
        REFERENCES TIPO_INGRESO(ID),

    FOREIGN KEY (ID_VIGENCIA) 
        REFERENCES VIGENCIA(ID),

    FOREIGN KEY (ID_CLASIFICACION_NOMBRE_CUENTA) 
        REFERENCES CLASIFICACION_NOMBRE_CUENTA(ID),

    FOREIGN KEY (ID_TIPO_EGRESO) 
        REFERENCES TIPO_EGRESO(ID)
);